🔥 This is massively outdated and not maintained. Feel free to use it as inspirations, but _don't_ use it verbatim. 🔥

asciidoctor-archetype
=====================

A maven archetype to bootstrap an asciidoctor toolchain. No prerequisites other than Maven & Java required. 
(Caveat: until the asciidoctor maven plugin 1.5 is released, you will need to build it yourself. Look there: https://github.com/asciidoctor/asciidoctor-maven-plugin/ )
It also features an assembly that includes all files to recreate the documentation artifacts from the distribution package.

The required backends and the working dzslides fork for that are linked as submodules for easy updating from 

* https://github.com/asciidoctor/asciidoctor-backends and 
* https://github.com/mojavelinux/dzslides


Quick Start
-----------
. Clone this repository and update the submodules
[source, sh]
git clone https://github.com/wwerner/asciidoctor-archetype.git
git submodule init
git submodule update

. Build and install the archetype
[source, sh]
mvn install

. Go to the folder where you want to create your documentation project and say
[source, sh]
mvn archetype:generate -DarchetypeGroupId=net.wolfgangwerner.writing -DarchetypeArtifactId=asciidoctor-archetype

. Edit the sample document/slides in <your project>/src/doc 
. Build the sample document/slides
[source, sh]
mvn install

. Pick up the results in <your project>/target/generated-docs
. Also take a look into the zip file. You should be able to extract it anywhere and run the build there.
